### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by zqs7985** [LolnationCH/Phone-Hub#1]
Nice!
At first it won't start,after check readme,so I need other 3 thing.If could make a whole package,that would be more convenient！
如果能整合其他三个组件做成一个完整包，就更好了，谢谢，很好用的小工具。

**Comment by LolnationCH** [comment]
Yes, the "Setup" section provides instruction for the other "exe" needed.

I didn't want to include them because:

- I did not make them, so I don't own them
- They could be updated to work with new Android Phone.
